spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:13306
    username: tata
    password: 198623onepiece
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true # 啟用服務發現
          lower-case-service-id: true # 服務 ID 轉換為小寫
      httpclient:
        connect-timeout: 5000       # 連線 timeout
        response-timeout: 10s       # 回應 timeout

eureka:
  instance:
    prefer-ip-address: true
    ip-address: ${SERVER_HOST:127.0.0.1}
  client:
    service-url:
      defaultZone: http://${EUREKA_SERVER_HOST:127.0.0.1}:${EUREKA_SERVER_PORT:8761}/eureka/ # Eureka 服務地址